services:
  baseplatform:
    build: 
      context: ./base
      dockerfile: Dockerfile
    container_name: baseplatform
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=FastAPI Base Platform
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
    volumes:
      - ./base:/app
      - ./sessions:/app/etc/sessions
    restart: unless-stopped
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true