services:
  baseplatform:
    build:  .
    container_name: baseplatform
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=FastAPI Base Platform
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5000
    volumes:
      - ./:/app
    restart: unless-stopped
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true